/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the GetUser2faStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUser2faStatus200Response{}

// GetUser2faStatus200Response struct for GetUser2faStatus200Response
type GetUser2faStatus200Response struct {
	// Is 2FA enabled for this user
	Enabled bool `json:"enabled"`
	// Number of remaining backup codes for this user
	BackupCodesRemaining int64 `json:"backup_codes_remaining"`
	AdditionalProperties map[string]interface{}
}

type _GetUser2faStatus200Response GetUser2faStatus200Response

// NewGetUser2faStatus200Response instantiates a new GetUser2faStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUser2faStatus200Response(enabled bool, backupCodesRemaining int64) *GetUser2faStatus200Response {
	this := GetUser2faStatus200Response{}
	this.Enabled = enabled
	this.BackupCodesRemaining = backupCodesRemaining
	return &this
}

// NewGetUser2faStatus200ResponseWithDefaults instantiates a new GetUser2faStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUser2faStatus200ResponseWithDefaults() *GetUser2faStatus200Response {
	this := GetUser2faStatus200Response{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *GetUser2faStatus200Response) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *GetUser2faStatus200Response) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *GetUser2faStatus200Response) SetEnabled(v bool) {
	o.Enabled = v
}

// GetBackupCodesRemaining returns the BackupCodesRemaining field value
func (o *GetUser2faStatus200Response) GetBackupCodesRemaining() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BackupCodesRemaining
}

// GetBackupCodesRemainingOk returns a tuple with the BackupCodesRemaining field value
// and a boolean to check if the value has been set.
func (o *GetUser2faStatus200Response) GetBackupCodesRemainingOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackupCodesRemaining, true
}

// SetBackupCodesRemaining sets field value
func (o *GetUser2faStatus200Response) SetBackupCodesRemaining(v int64) {
	o.BackupCodesRemaining = v
}

func (o GetUser2faStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUser2faStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["backup_codes_remaining"] = o.BackupCodesRemaining

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetUser2faStatus200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"backup_codes_remaining",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUser2faStatus200Response := _GetUser2faStatus200Response{}

	err = json.Unmarshal(data, &varGetUser2faStatus200Response)

	if err != nil {
		return err
	}

	*o = GetUser2faStatus200Response(varGetUser2faStatus200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "backup_codes_remaining")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetUser2faStatus200Response struct {
	value *GetUser2faStatus200Response
	isSet bool
}

func (v NullableGetUser2faStatus200Response) Get() *GetUser2faStatus200Response {
	return v.value
}

func (v *NullableGetUser2faStatus200Response) Set(val *GetUser2faStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUser2faStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUser2faStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUser2faStatus200Response(val *GetUser2faStatus200Response) *NullableGetUser2faStatus200Response {
	return &NullableGetUser2faStatus200Response{value: val, isSet: true}
}

func (v NullableGetUser2faStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUser2faStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
