/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RequestToken200Response - struct for RequestToken200Response
type RequestToken200Response struct {
	RefreshToken200Response      *RefreshToken200Response
	RequestToken200ResponseOneOf *RequestToken200ResponseOneOf
}

// RefreshToken200ResponseAsRequestToken200Response is a convenience function that returns RefreshToken200Response wrapped in RequestToken200Response
func RefreshToken200ResponseAsRequestToken200Response(v *RefreshToken200Response) RequestToken200Response {
	return RequestToken200Response{
		RefreshToken200Response: v,
	}
}

// RequestToken200ResponseOneOfAsRequestToken200Response is a convenience function that returns RequestToken200ResponseOneOf wrapped in RequestToken200Response
func RequestToken200ResponseOneOfAsRequestToken200Response(v *RequestToken200ResponseOneOf) RequestToken200Response {
	return RequestToken200Response{
		RequestToken200ResponseOneOf: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *RequestToken200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RefreshToken200Response
	err = newStrictDecoder(data).Decode(&dst.RefreshToken200Response)
	if err == nil {
		jsonRefreshToken200Response, _ := json.Marshal(dst.RefreshToken200Response)
		if string(jsonRefreshToken200Response) == "{}" { // empty struct
			dst.RefreshToken200Response = nil
		} else {
			if err = validator.Validate(dst.RefreshToken200Response); err != nil {
				dst.RefreshToken200Response = nil
			} else {
				match++
			}
		}
	} else {
		dst.RefreshToken200Response = nil
	}

	// try to unmarshal data into RequestToken200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.RequestToken200ResponseOneOf)
	if err == nil {
		jsonRequestToken200ResponseOneOf, _ := json.Marshal(dst.RequestToken200ResponseOneOf)
		if string(jsonRequestToken200ResponseOneOf) == "{}" { // empty struct
			dst.RequestToken200ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.RequestToken200ResponseOneOf); err != nil {
				dst.RequestToken200ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.RequestToken200ResponseOneOf = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RefreshToken200Response = nil
		dst.RequestToken200ResponseOneOf = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RequestToken200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RequestToken200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RequestToken200Response) MarshalJSON() ([]byte, error) {
	if src.RefreshToken200Response != nil {
		return json.Marshal(&src.RefreshToken200Response)
	}

	if src.RequestToken200ResponseOneOf != nil {
		return json.Marshal(&src.RequestToken200ResponseOneOf)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RequestToken200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.RefreshToken200Response != nil {
		return obj.RefreshToken200Response
	}

	if obj.RequestToken200ResponseOneOf != nil {
		return obj.RequestToken200ResponseOneOf
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RequestToken200Response) GetActualInstanceValue() interface{} {
	if obj.RefreshToken200Response != nil {
		return *obj.RefreshToken200Response
	}

	if obj.RequestToken200ResponseOneOf != nil {
		return *obj.RequestToken200ResponseOneOf
	}

	// all schemas are nil
	return nil
}

type NullableRequestToken200Response struct {
	value *RequestToken200Response
	isSet bool
}

func (v NullableRequestToken200Response) Get() *RequestToken200Response {
	return v.value
}

func (v *NullableRequestToken200Response) Set(val *RequestToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestToken200Response(val *RequestToken200Response) *NullableRequestToken200Response {
	return &NullableRequestToken200Response{value: val, isSet: true}
}

func (v NullableRequestToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
