/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the LoginWith2FARequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginWith2FARequest{}

// LoginWith2FARequest struct for LoginWith2FARequest
type LoginWith2FARequest struct {
	ChallengeToken       string `json:"challenge_token"`
	Code                 string `json:"code"`
	AdditionalProperties map[string]interface{}
}

type _LoginWith2FARequest LoginWith2FARequest

// NewLoginWith2FARequest instantiates a new LoginWith2FARequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginWith2FARequest(challengeToken string, code string) *LoginWith2FARequest {
	this := LoginWith2FARequest{}
	this.ChallengeToken = challengeToken
	this.Code = code
	return &this
}

// NewLoginWith2FARequestWithDefaults instantiates a new LoginWith2FARequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginWith2FARequestWithDefaults() *LoginWith2FARequest {
	this := LoginWith2FARequest{}
	return &this
}

// GetChallengeToken returns the ChallengeToken field value
func (o *LoginWith2FARequest) GetChallengeToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChallengeToken
}

// GetChallengeTokenOk returns a tuple with the ChallengeToken field value
// and a boolean to check if the value has been set.
func (o *LoginWith2FARequest) GetChallengeTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChallengeToken, true
}

// SetChallengeToken sets field value
func (o *LoginWith2FARequest) SetChallengeToken(v string) {
	o.ChallengeToken = v
}

// GetCode returns the Code field value
func (o *LoginWith2FARequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *LoginWith2FARequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *LoginWith2FARequest) SetCode(v string) {
	o.Code = v
}

func (o LoginWith2FARequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginWith2FARequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["challenge_token"] = o.ChallengeToken
	toSerialize["code"] = o.Code

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LoginWith2FARequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"challenge_token",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginWith2FARequest := _LoginWith2FARequest{}

	err = json.Unmarshal(data, &varLoginWith2FARequest)

	if err != nil {
		return err
	}

	*o = LoginWith2FARequest(varLoginWith2FARequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "challenge_token")
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoginWith2FARequest struct {
	value *LoginWith2FARequest
	isSet bool
}

func (v NullableLoginWith2FARequest) Get() *LoginWith2FARequest {
	return v.value
}

func (v *NullableLoginWith2FARequest) Set(val *LoginWith2FARequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginWith2FARequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginWith2FARequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginWith2FARequest(val *LoginWith2FARequest) *NullableLoginWith2FARequest {
	return &NullableLoginWith2FARequest{value: val, isSet: true}
}

func (v NullableLoginWith2FARequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginWith2FARequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
