/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the CheckVersion200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckVersion200Response{}

// CheckVersion200Response Check Version object
type CheckVersion200Response struct {
	// Current version string
	Current NullableString `json:"current"`
	// Latest version string
	Latest NullableString `json:"latest"`
	// Whether there's an update available
	UpdateAvailable      bool `json:"update_available"`
	AdditionalProperties map[string]interface{}
}

type _CheckVersion200Response CheckVersion200Response

// NewCheckVersion200Response instantiates a new CheckVersion200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckVersion200Response(current NullableString, latest NullableString, updateAvailable bool) *CheckVersion200Response {
	this := CheckVersion200Response{}
	this.Current = current
	this.Latest = latest
	this.UpdateAvailable = updateAvailable
	return &this
}

// NewCheckVersion200ResponseWithDefaults instantiates a new CheckVersion200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckVersion200ResponseWithDefaults() *CheckVersion200Response {
	this := CheckVersion200Response{}
	return &this
}

// GetCurrent returns the Current field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CheckVersion200Response) GetCurrent() string {
	if o == nil || o.Current.Get() == nil {
		var ret string
		return ret
	}

	return *o.Current.Get()
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckVersion200Response) GetCurrentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Current.Get(), o.Current.IsSet()
}

// SetCurrent sets field value
func (o *CheckVersion200Response) SetCurrent(v string) {
	o.Current.Set(&v)
}

// GetLatest returns the Latest field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CheckVersion200Response) GetLatest() string {
	if o == nil || o.Latest.Get() == nil {
		var ret string
		return ret
	}

	return *o.Latest.Get()
}

// GetLatestOk returns a tuple with the Latest field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckVersion200Response) GetLatestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Latest.Get(), o.Latest.IsSet()
}

// SetLatest sets field value
func (o *CheckVersion200Response) SetLatest(v string) {
	o.Latest.Set(&v)
}

// GetUpdateAvailable returns the UpdateAvailable field value
func (o *CheckVersion200Response) GetUpdateAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UpdateAvailable
}

// GetUpdateAvailableOk returns a tuple with the UpdateAvailable field value
// and a boolean to check if the value has been set.
func (o *CheckVersion200Response) GetUpdateAvailableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateAvailable, true
}

// SetUpdateAvailable sets field value
func (o *CheckVersion200Response) SetUpdateAvailable(v bool) {
	o.UpdateAvailable = v
}

func (o CheckVersion200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckVersion200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current"] = o.Current.Get()
	toSerialize["latest"] = o.Latest.Get()
	toSerialize["update_available"] = o.UpdateAvailable

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CheckVersion200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current",
		"latest",
		"update_available",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckVersion200Response := _CheckVersion200Response{}

	err = json.Unmarshal(data, &varCheckVersion200Response)

	if err != nil {
		return err
	}

	*o = CheckVersion200Response(varCheckVersion200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "current")
		delete(additionalProperties, "latest")
		delete(additionalProperties, "update_available")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCheckVersion200Response struct {
	value *CheckVersion200Response
	isSet bool
}

func (v NullableCheckVersion200Response) Get() *CheckVersion200Response {
	return v.value
}

func (v *NullableCheckVersion200Response) Set(val *CheckVersion200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckVersion200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckVersion200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckVersion200Response(val *CheckVersion200Response) *NullableCheckVersion200Response {
	return &NullableCheckVersion200Response{value: val, isSet: true}
}

func (v NullableCheckVersion200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckVersion200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
