/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the EnableUser2fa200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableUser2fa200Response{}

// EnableUser2fa200Response struct for EnableUser2fa200Response
type EnableUser2fa200Response struct {
	// Backup codes
	BackupCodes          []string `json:"backup_codes"`
	AdditionalProperties map[string]interface{}
}

type _EnableUser2fa200Response EnableUser2fa200Response

// NewEnableUser2fa200Response instantiates a new EnableUser2fa200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableUser2fa200Response(backupCodes []string) *EnableUser2fa200Response {
	this := EnableUser2fa200Response{}
	this.BackupCodes = backupCodes
	return &this
}

// NewEnableUser2fa200ResponseWithDefaults instantiates a new EnableUser2fa200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableUser2fa200ResponseWithDefaults() *EnableUser2fa200Response {
	this := EnableUser2fa200Response{}
	return &this
}

// GetBackupCodes returns the BackupCodes field value
func (o *EnableUser2fa200Response) GetBackupCodes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BackupCodes
}

// GetBackupCodesOk returns a tuple with the BackupCodes field value
// and a boolean to check if the value has been set.
func (o *EnableUser2fa200Response) GetBackupCodesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupCodes, true
}

// SetBackupCodes sets field value
func (o *EnableUser2fa200Response) SetBackupCodes(v []string) {
	o.BackupCodes = v
}

func (o EnableUser2fa200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableUser2fa200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backup_codes"] = o.BackupCodes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EnableUser2fa200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backup_codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnableUser2fa200Response := _EnableUser2fa200Response{}

	err = json.Unmarshal(data, &varEnableUser2fa200Response)

	if err != nil {
		return err
	}

	*o = EnableUser2fa200Response(varEnableUser2fa200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "backup_codes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEnableUser2fa200Response struct {
	value *EnableUser2fa200Response
	isSet bool
}

func (v NullableEnableUser2fa200Response) Get() *EnableUser2fa200Response {
	return v.value
}

func (v *NullableEnableUser2fa200Response) Set(val *EnableUser2fa200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableUser2fa200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableUser2fa200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableUser2fa200Response(val *EnableUser2fa200Response) *NullableEnableUser2fa200Response {
	return &NullableEnableUser2fa200Response{value: val, isSet: true}
}

func (v NullableEnableUser2fa200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableUser2fa200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
