/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the EnableUser2faRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableUser2faRequest{}

// EnableUser2faRequest struct for EnableUser2faRequest
type EnableUser2faRequest struct {
	Code                 string `json:"code"`
	AdditionalProperties map[string]interface{}
}

type _EnableUser2faRequest EnableUser2faRequest

// NewEnableUser2faRequest instantiates a new EnableUser2faRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableUser2faRequest(code string) *EnableUser2faRequest {
	this := EnableUser2faRequest{}
	this.Code = code
	return &this
}

// NewEnableUser2faRequestWithDefaults instantiates a new EnableUser2faRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableUser2faRequestWithDefaults() *EnableUser2faRequest {
	this := EnableUser2faRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *EnableUser2faRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *EnableUser2faRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *EnableUser2faRequest) SetCode(v string) {
	o.Code = v
}

func (o EnableUser2faRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableUser2faRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EnableUser2faRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnableUser2faRequest := _EnableUser2faRequest{}

	err = json.Unmarshal(data, &varEnableUser2faRequest)

	if err != nil {
		return err
	}

	*o = EnableUser2faRequest(varEnableUser2faRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEnableUser2faRequest struct {
	value *EnableUser2faRequest
	isSet bool
}

func (v NullableEnableUser2faRequest) Get() *EnableUser2faRequest {
	return v.value
}

func (v *NullableEnableUser2faRequest) Set(val *EnableUser2faRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableUser2faRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableUser2faRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableUser2faRequest(val *EnableUser2faRequest) *NullableEnableUser2faRequest {
	return &NullableEnableUser2faRequest{value: val, isSet: true}
}

func (v NullableEnableUser2faRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableUser2faRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
