/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the SetupUser2fa200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetupUser2fa200Response{}

// SetupUser2fa200Response struct for SetupUser2fa200Response
type SetupUser2fa200Response struct {
	// TOTP Secret
	Secret string `json:"secret"`
	// OTP Auth URL for QR Code generation
	OtpauthUrl           string `json:"otpauth_url"`
	AdditionalProperties map[string]interface{}
}

type _SetupUser2fa200Response SetupUser2fa200Response

// NewSetupUser2fa200Response instantiates a new SetupUser2fa200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetupUser2fa200Response(secret string, otpauthUrl string) *SetupUser2fa200Response {
	this := SetupUser2fa200Response{}
	this.Secret = secret
	this.OtpauthUrl = otpauthUrl
	return &this
}

// NewSetupUser2fa200ResponseWithDefaults instantiates a new SetupUser2fa200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetupUser2fa200ResponseWithDefaults() *SetupUser2fa200Response {
	this := SetupUser2fa200Response{}
	return &this
}

// GetSecret returns the Secret field value
func (o *SetupUser2fa200Response) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *SetupUser2fa200Response) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *SetupUser2fa200Response) SetSecret(v string) {
	o.Secret = v
}

// GetOtpauthUrl returns the OtpauthUrl field value
func (o *SetupUser2fa200Response) GetOtpauthUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtpauthUrl
}

// GetOtpauthUrlOk returns a tuple with the OtpauthUrl field value
// and a boolean to check if the value has been set.
func (o *SetupUser2fa200Response) GetOtpauthUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpauthUrl, true
}

// SetOtpauthUrl sets field value
func (o *SetupUser2fa200Response) SetOtpauthUrl(v string) {
	o.OtpauthUrl = v
}

func (o SetupUser2fa200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetupUser2fa200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secret"] = o.Secret
	toSerialize["otpauth_url"] = o.OtpauthUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetupUser2fa200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secret",
		"otpauth_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetupUser2fa200Response := _SetupUser2fa200Response{}

	err = json.Unmarshal(data, &varSetupUser2fa200Response)

	if err != nil {
		return err
	}

	*o = SetupUser2fa200Response(varSetupUser2fa200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "secret")
		delete(additionalProperties, "otpauth_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetupUser2fa200Response struct {
	value *SetupUser2fa200Response
	isSet bool
}

func (v NullableSetupUser2fa200Response) Get() *SetupUser2fa200Response {
	return v.value
}

func (v *NullableSetupUser2fa200Response) Set(val *SetupUser2fa200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSetupUser2fa200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSetupUser2fa200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetupUser2fa200Response(val *SetupUser2fa200Response) *NullableSetupUser2fa200Response {
	return &NullableSetupUser2fa200Response{value: val, isSet: true}
}

func (v NullableSetupUser2fa200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetupUser2fa200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
