/*
Nginx Proxy Manager API

This is the official API documentation for Nginx Proxy Manager.  Most endpoints require authentication via Bearer Token (JWT). You can generate a token by logging in via the `POST /tokens` endpoint.  For more information, visit the [Nginx Proxy Manager Documentation](https://nginxproxymanager.com).

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nginxproxymanager

import (
	"encoding/json"
	"fmt"
)

// checks if the RequestToken200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestToken200ResponseOneOf{}

// RequestToken200ResponseOneOf Token object
type RequestToken200ResponseOneOf struct {
	// Whether this token request requires two-factor authentication
	Requires2fa bool `json:"requires_2fa"`
	// Challenge Token used in subsequent 2FA verification
	ChallengeToken       string `json:"challenge_token"`
	AdditionalProperties map[string]interface{}
}

type _RequestToken200ResponseOneOf RequestToken200ResponseOneOf

// NewRequestToken200ResponseOneOf instantiates a new RequestToken200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestToken200ResponseOneOf(requires2fa bool, challengeToken string) *RequestToken200ResponseOneOf {
	this := RequestToken200ResponseOneOf{}
	this.Requires2fa = requires2fa
	this.ChallengeToken = challengeToken
	return &this
}

// NewRequestToken200ResponseOneOfWithDefaults instantiates a new RequestToken200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestToken200ResponseOneOfWithDefaults() *RequestToken200ResponseOneOf {
	this := RequestToken200ResponseOneOf{}
	return &this
}

// GetRequires2fa returns the Requires2fa field value
func (o *RequestToken200ResponseOneOf) GetRequires2fa() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Requires2fa
}

// GetRequires2faOk returns a tuple with the Requires2fa field value
// and a boolean to check if the value has been set.
func (o *RequestToken200ResponseOneOf) GetRequires2faOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Requires2fa, true
}

// SetRequires2fa sets field value
func (o *RequestToken200ResponseOneOf) SetRequires2fa(v bool) {
	o.Requires2fa = v
}

// GetChallengeToken returns the ChallengeToken field value
func (o *RequestToken200ResponseOneOf) GetChallengeToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChallengeToken
}

// GetChallengeTokenOk returns a tuple with the ChallengeToken field value
// and a boolean to check if the value has been set.
func (o *RequestToken200ResponseOneOf) GetChallengeTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChallengeToken, true
}

// SetChallengeToken sets field value
func (o *RequestToken200ResponseOneOf) SetChallengeToken(v string) {
	o.ChallengeToken = v
}

func (o RequestToken200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestToken200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requires_2fa"] = o.Requires2fa
	toSerialize["challenge_token"] = o.ChallengeToken

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RequestToken200ResponseOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requires_2fa",
		"challenge_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestToken200ResponseOneOf := _RequestToken200ResponseOneOf{}

	err = json.Unmarshal(data, &varRequestToken200ResponseOneOf)

	if err != nil {
		return err
	}

	*o = RequestToken200ResponseOneOf(varRequestToken200ResponseOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requires_2fa")
		delete(additionalProperties, "challenge_token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRequestToken200ResponseOneOf struct {
	value *RequestToken200ResponseOneOf
	isSet bool
}

func (v NullableRequestToken200ResponseOneOf) Get() *RequestToken200ResponseOneOf {
	return v.value
}

func (v *NullableRequestToken200ResponseOneOf) Set(val *RequestToken200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestToken200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestToken200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestToken200ResponseOneOf(val *RequestToken200ResponseOneOf) *NullableRequestToken200ResponseOneOf {
	return &NullableRequestToken200ResponseOneOf{value: val, isSet: true}
}

func (v NullableRequestToken200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestToken200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
